### ISSUE TITLE
Morning Session - 25/01/23

### ISSUE THREAD

**Issue by roodjinocherilus** [fithamlak/Awsome-books-ES6#2]
🎉Good job so far!
Your project looks nice and some of the key features are working such as:

Highlights
✅ Great Github flow
✅ Meaningful commit messages
✅ Easy to understand code
✅ ES6 Modules

Things you can improve:

- Try giving the modules a more concise and descriptive name
- [ ]  see the indentation in index.html, the good practices recommend only 2 spaces.-
- It is not possible to add multiple books at the same time without going to the other navigation tabs
- You forgot to add the " How to install and run the project" part

**Comment by fithamlak** [comment]
Thank you for your feedback, I will do it as soon as possible

**Comment by fithamlak** [comment]
Thank you I Implement all suggestions, and you can get it in another repo here https://github.com/fithamlak/Awesome-ES6-peer-Review
